#require(tidyverse)
#require(ggplot2)
#require(gridExtra)

#' Load Raw Data
#'
#' \code{load_raw_data} Pulls data from a file path to be passed to other functions.
#'
#' This function takes the file name and data path is a generic function: methods can be defined for it directly or via the
#' \code{\link{ggplot2}} group generic. For this to work properly, the arguments
#' \code{...} should be generated from the functions \code{\link{load_raw_data},
#' and \code{\link{confirm_columns}.
#'
#' @param ... Name of the file - this must be in the form of a string.
#' @param ... The file path is an optional argument and is set to call from within the directory
#' @return If all inputs are valid the output will produce a file which can be passed to \code{\link{plot_histogram}.
#'   If inputs are invalid, an error message will be generated.
#' @examples
#' load_raw_data("supp_table4.csv")
#'
#' \dontrun{
#' load_raw_data("file name which does not exist")
#' }

load_raw_data <- function(filename, data_path="analysis/data/raw_data") {
  fname <- file.path(data_path, filename)
  print(fname)
  if(!file.exists(fname)) {
    stop(cat("Could not find file ", fname), call. = FALSE)
  }
  df <- read.csv(file.path(data_path, filename))
}


#' Confirm Columns
#'
#' \code{confirm_columns} Checks correct columns exist within dataframe.
#'
#' This function confirms that the column name exists, which is a necessary pre-requisite for passing to the function \code{\link{plot_histogram}. It receives the output of \code{\link{load_raw_data}
#'
#' @param ... Name of the file.
#' @param ... Column name - this must be in the form of a string.
#' @return If all inputs are valid the output will produce a file which can be passed to \code{\link{plot_histogram}.
#'   If inputs are invalid, an error message will be generated.
#' @examples
#' confirm_columns("supp_table4.csv")
#'
#' \dontrun{
#' confirm_columns(column, "Missing column")
#' }

confirm_columns <- function(input_data, colname) {
  # Confirm that the column name exists
  if(is.null(input_data[[colname]])) {
    stop(cat("Missing column ", colname, "in data frame ", deparse(substitute(input_data))), call. = FALSE)
  }
}


#' Plot histogram
#'
#' \code{plot_histogram} Plots a pre-specified histogram powered by ggplot.
#'
#' This is a generic function: methods can be defined for it directly or via the
#' \code{\link{ggplot2}} group generic. For this to work properly, the arguments
#' \code{...} should be generated from the functions \code{\link{load_raw_data},
#' and \code{\link{confirm_columns}.
#'
#' @param ... The input data which should be a matrix or dataframe has been generated by @seealso
#'   \code{\link{load_raw_data}}.
#' @param ... The column name which should be a string
#' @return If all inputs are valid the output will produce a simple histogram.
#'   If inputs are invalid, an error message will be generated.
#' @examples
#' plot_histogram(newst, "Avg.lifetime", binwidth=0.5, xh=10, yh=160)
#'
#' @import ggplot2
#'
#' \dontrun{
#' plot_histogram("a")
#' }
plot_histogram <- function(input_data, colname, binwidth=0.5, xh=10, yh=160) {
  # Confirm that the columns exist
  confirm_columns(input_data, colname)

  # Generate basic plot object
  fig <- ggplot(input_data, aes_string(x=colname)) +
    geom_histogram(binwidth=binwidth) + xlim(0, xh) + ylim(0, yh)
  fig
}
# This goes in paper.Rmd
# # Load data and make plots
# data_3a <- load_raw_data("supp_table4.csv")
# plot_3a <- plot_histogram(data_3a, "Avg.lifetime", binwidth=0.5, xh=10, yh=160)
#
# data_3b <- load_raw_data("supp_table6.csv")
# plot_3b <- plot_histogram(data_3b, "Elongation.Rate..nt.s.", binwidth=05, xh=75, yh=70)
#
# # Plot on same figure
# grid.arrange(plot_3a, plot_3b, ncol=2)
